print('Olá, eu vou te ajudar a calcular o quanto você ganha por mês.')
valor = float(input('Por favor, digite o quanto você recebe em R$ por hora trabalhada: '))
valor_formatado = f"R$ {valor:.2f}".replace('.',',')
print(f'Ok, entendi, você ganha {valor_formatado} por hora trabalhada.') 
horatrabalhada = float(input('Agora, por favor, digite quantas horas você trabalha por mês: '))
print(f'Ok, entendi, você trabalha {horatrabalhada} horas por mês.') 
salario = valor*horatrabalhada
salario_formatado = f"R$ {salario:.2f}".replace('.',',')
desconto_total = 24
salario_liquido = salario * (1- 24/100)
salario_liquido_formatado = f"R$ {salario_liquido:.2f}".replace('.',',')
desconto_ir = salario * (1 - 89/100)
desconto_ir_formatado = f"R$ {desconto_ir:.2f}".replace('.',',')
desconto_inss = salario * (1 - 92/100)
desconto_inss_formatado = f"R$ {desconto_inss:.2f}".replace('.',',')
desconto_sindicato = salario * (1 - 95/100)
desconto_sindicato_formatado = f"R$ {desconto_sindicato:.2f}".replace('.',',')
print(f'Com base nos valores fornecidos anteriormente, seu salário bruto mensal é de {salario_formatado}.')
print(f'Sabendo-se que são descontados 11% para o Imposto de Renda, 8% para o INSS e 5% para o sindicato, vou te mostrar seu salário líquido.')
print(f'Considerando os descontos, seu salário líquido mensal é de {salario_liquido_formatado}.')
print(f'O desconto referente ao Imposto de renda é de {desconto_ir_formatado}.')
print(f'O desconto referente ao INSS é de {desconto_inss_formatado}.')
print(f'O desconto referente ao sindicato é de {desconto_sindicato_formatado}.')